#!/bin/bash

rm -rvf world

world_shp() {
  mkdir -p build
  curl -z build/ne_$1_admin_0_countries.zip -o build/ne_$1_admin_0_countries.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
  unzip -od build build/ne_$1_admin_0_countries.zip
  chmod a-x build/ne_$1_admin_0_countries.*
}

world() {
  world_shp $1
  mkdir -p world
  geo2topo -q 1e4 -n countries=<( \
      shp2json -n build/ne_$1_admin_0_countries.shp \
        | ndjson-map '(d.id = d.properties.admin, delete d.properties, d)' \
        | ndjson-filter 'd.id !== "Antarctica"' \
        | geostitch -n) \
    | toposimplify -f -p 0.02 \
    | topomerge land=countries \
    > world/$1.json
}

world 110m
world 50m
